create database office;
use office;
create table Employee (EmployeeID integer primary key not null auto_increment, FirstName varchar(50) not null, LastName varchar(50) not null, DOJ date not null, DOB date not null, DeptID integer not null, LocID integer not null, EmpMail varchar(70) not null, EmpPH bigint not null);
create table Department (DeptID integer primary key not null auto_increment, DeptName varchar(20) not null);
create table Location (LocID integer primary key not null auto_increment, LocName varchar(30) not null);
drop table department;
drop table location;
drop table employee;
show tables;
desc Employee;
desc Department;
desc Location;
insert into location (locname) values ('Mumbai');
insert into location (locname) values ('Pune');
insert into location (locname) values ('Hyderabad');
insert into location (locname) values ('Bangalore');
insert into location (locname) values ('Delhi');
insert into department (deptname) values ('Human Resources');
insert into department (deptname) values ('IT');
insert into department (deptname) values ('Finance');
insert into department (deptname) values ('Marketing');
insert into department (deptname) values ('Sales');
select * from department;
select * from location;
select * from employee;
update department set deptname='HR' where DEPTID = '1'; 
alter table employee modify EmpPH varchar(13) NOT NULL;